apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: chat-app-database-container
        image: mongo:latest
        ports:
        - containerPort: 27017 # Fixed typo: "contanerPort" → "containerPort"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME # Fixed typo: "MONGO_INITD" → "MONGO_INITDB"
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD # Fixed typo: "MONGO_INITD" → "MONGO_INITDB"
          value: root
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
